
'use server';

/**
 * @fileOverview Customizes interview questions based on a provided job description, interview type, style, targeted skills, and other factors.
 *               For "take-home" style, it delegates to a specialized flow.
 *
 * - customizeInterviewQuestions - A function that customizes interview questions or delegates take-home assignment generation.
 * - CustomizeInterviewQuestionsInput - The input type for the customizeInterviewQuestions function.
 * - CustomizeInterviewQuestionsOutput - The return type for the customizeInterviewQuestions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { AMAZON_LEADERSHIP_PRINCIPLES } from '@/lib/constants';
import { getTechnologyBriefTool } from '../tools/technology-tools';
import { generateTakeHomeAssignment } from './generate-take-home-assignment';
import type { GenerateTakeHomeAssignmentInput } from './generate-take-home-assignment';

const CustomizeInterviewQuestionsInputSchema = z.object({
  jobTitle: z
    .string()
    .optional()
    .describe('The job title to customize the interview questions for. This is a key input for tailoring technical depth and focus.'),
  jobDescription: z
    .string()
    .optional()
    .describe('The job description to customize the interview questions for. Use this to extract key responsibilities and technologies.'),
  resume: z
    .string()
    .optional()
    .describe('The user resume to provide context about the candidate\'s background. Use this to subtly angle questions, but do not ask questions directly *about* the resume unless it\'s a behavioral question about past experiences.'),
  interviewType: z
    .enum(['product sense', 'technical system design', 'behavioral'])
    .describe('The type of interview to generate questions for.'),
  interviewStyle: z
    .enum(['simple-qa', 'case-study', 'take-home'])
    .describe('The style of the interview: simple Q&A, multi-turn case study, or take-home assignment.'),
  faangLevel: z
    .string()
    .optional()
    .describe('The target FAANG level for difficulty adjustment. This is critical for calibrating question complexity.'),
  targetedSkills: z
    .array(z.string())
    .optional()
    .describe('Specific skills the user wants to focus on. Prioritize questions that assess these skills.'),
  targetCompany: z
    .string()
    .optional()
    .describe('The target company the user is interviewing for (e.g., Amazon, Google). This can influence question style and thematic focus.'),
  interviewFocus: z
    .string()
    .optional()
    .describe('A specific focus area or sub-topic provided by the user to further narrow down the interview content. This should refine questions within the broader interview type and targeted skills.'),
});

export type CustomizeInterviewQuestionsInput = z.infer<
  typeof CustomizeInterviewQuestionsInputSchema
>;

const CustomizeInterviewQuestionsOutputSchema = z.object({
  customizedQuestions: z
    .array(z.string())
    .describe('An array of customized interview questions. For "take-home" style, this will contain a single, comprehensive assignment description generated by a specialized flow.'),
});

export type CustomizeInterviewQuestionsOutput = z.infer<
  typeof CustomizeInterviewQuestionsOutputSchema
>;

export async function customizeInterviewQuestions(
  input: CustomizeInterviewQuestionsInput
): Promise<CustomizeInterviewQuestionsOutput> {
  if (input.interviewStyle === 'take-home') {
    const takeHomeInput: GenerateTakeHomeAssignmentInput = {
      interviewType: input.interviewType,
      jobTitle: input.jobTitle,
      jobDescription: input.jobDescription,
      faangLevel: input.faangLevel || 'L5', // Provide a default if optional in main but required in specialist
      targetedSkills: input.targetedSkills,
      targetCompany: input.targetCompany,
      interviewFocus: input.interviewFocus,
    };
    try {
      const takeHomeOutput = await generateTakeHomeAssignment(takeHomeInput);
      return { customizedQuestions: [takeHomeOutput.assignmentText] };
    } catch (error) {
      console.error("Error generating take-home assignment:", error);
      // Fallback to a generic error message or a very simple assignment
      return { customizedQuestions: ["Failed to generate take-home assignment. The detailed problem statement could not be created. Please ensure all relevant fields like 'Job Title', 'Job Description', and 'Interview Focus' are as specific as possible. You can try configuring a simpler interview style or contact support."] };
    }
  }
  return customizeInterviewQuestionsMainFlow(input);
}

const mainPrompt = ai.definePrompt({
  name: 'customizeInterviewQuestionsMainPrompt', // Renamed to avoid conflict
  tools: [getTechnologyBriefTool],
  input: {
    schema: CustomizeInterviewQuestionsInputSchema,
  },
  output: {
    // This prompt will only handle simple-qa and case-study, 
    // so its output is directly an array of questions.
    schema: CustomizeInterviewQuestionsOutputSchema 
  },
  prompt: `You are an expert Interview Architect AI, highly skilled in crafting FAANG-level interview questions.
Your primary function is to generate tailored interview content for 'simple-qa' or 'case-study' styles based on the detailed specifications provided.
You must meticulously consider all inputs to create relevant, challenging, and insightful questions.
DO NOT attempt to generate 'take-home' assignments; that is handled by a specialized process. If for some reason you are asked to generate a take-home assignment here, state that it's handled separately.

**Core Instructions & Persona:**
- Your persona is that of a seasoned hiring manager and curriculum designer from a top-tier tech company (like Google, Meta, or Amazon).
- You are creating questions for a mock interview, designed to help candidates prepare effectively.
- Adhere strictly to the number of questions specified for each style.
- Ensure every question directly reflects the provided inputs.

**General Principles for All Questions:**
1.  **Relevance & Specificity:** Questions must be directly pertinent to the specified 'interviewType'. If 'jobTitle' and 'jobDescription' are provided, questions must be deeply tailored to the responsibilities, technologies, and domain mentioned. For instance, "Senior Product Manager, Machine Learning" requires significantly more technical depth in product questions than a "Product Manager, Growth."
2.  **Difficulty Calibration:** All content must be precisely calibrated to the 'faangLevel'. An L3 question should be fundamentally different in scope and complexity from an L6 question.
3.  **Clarity & Conciseness:** Questions must be unambiguous, clear, and easy to understand. Avoid jargon unless it's central to the role defined by 'jobTitle' or 'jobDescription'.
4.  **Skill Assessment:** Design questions to effectively evaluate 'targetedSkills' (if provided) or core competencies expected for the 'interviewType' and 'faangLevel'. If an 'interviewFocus' is provided, this should be a primary theme, especially for case studies.
5.  **Open-Ended:** Questions should encourage detailed, reasoned responses, not simple yes/no answers.
6.  **Resume Context:** Use the 'resume' (if provided) *only* for contextual understanding of the candidate's potential background. This might subtly influence the angle or examples in questions, but do not generate questions *directly about* the resume content itself, unless the 'interviewType' is "behavioral" and the question explicitly asks for past experiences.
7.  **Tool Usage for Clarity:** If the 'jobDescription' or 'targetedSkills' mention specific technologies crucial for the role, and you need a concise overview to ensure your questions are deeply relevant and appropriately targeted, you may use the \`getTechnologyBriefTool\` to get a summary. Focus on incorporating insights from the tool to make your questions more specific and context-aware. Do not just repeat the tool's output; integrate its information to create better questions.

**Interview Context & Inputs to Consider:**
{{#if jobTitle}}Job Title: {{{jobTitle}}}{{/if}}
{{#if jobDescription}}Job Description: {{{jobDescription}}}{{/if}}
{{#if resume}}Candidate Resume Context: {{{resume}}}{{/if}}
Interview Type: {{{interviewType}}}
Interview Style: {{{interviewStyle}}}
{{#if faangLevel}}FAANG Level: {{{faangLevel}}}{{/if}}
{{#if targetCompany}}Target Company: {{{targetCompany}}}{{/if}}
{{#if targetedSkills.length}}
Targeted Skills:
{{#each targetedSkills}}
- {{{this}}}
{{/each}}
{{/if}}
{{#if interviewFocus}}Specific Focus: {{{interviewFocus}}}{{/if}}

**Style-Specific Question Generation Logic (for 'simple-qa' and 'case-study' ONLY):**

{{#if (eq interviewStyle "case-study")}}
**Case Study (Multi-turn) - Generate 5-7 questions total:**
Your goal is to simulate a multi-turn conversational deep-dive.
1.  **Internal Deliberation (Chain-of-Thought):**
    *   First, deeply analyze the 'interviewType', 'jobTitle', 'jobDescription', 'targetedSkills', and especially the 'interviewFocus' if provided.
    *   Based on this, brainstorm a single, rich, open-ended core scenario or problem statement. This scenario must be complex enough to sustain multiple follow-up questions and directly reflect the 'interviewFocus'.
    *   Then, devise 4-6 probing follow-up questions that logically extend from this core scenario. These follow-ups should explore different facets of the problem, challenge assumptions, and push the candidate to elaborate on their thinking process, trade-offs, and justifications, all while keeping the 'interviewFocus' in mind.
2.  **Output Structure:**
    *   The first string in the 'customizedQuestions' array MUST be the broad, initial scenario question.
    *   The subsequent strings in the array MUST be the probing follow-up questions.
    *   The entire set of questions should flow naturally, as if in a real-time conversation, starting broad and progressively narrowing focus or exploring related dimensions.
    *   Example of flow: Initial: "Design a new product for X market, with a specific focus on {{{interviewFocus}}}." Follow-ups: "Who are the key user segments for this {{{interviewFocus}}} and how would you prioritize them?", "What would be your MVP for {{{interviewFocus}}} and why?", "How would you measure success specifically for the {{{interviewFocus}}} aspect?", "What are the major risks related to {{{interviewFocus}}} and how would you mitigate them?".
    *   The questions should be tailored. For 'technical system design', the scenario would be a system to design, and follow-ups would probe architecture, components, scalability, etc., always relating back to the 'interviewFocus'. For 'product sense', it could be a product strategy or design challenge centered on the 'interviewFocus'. For 'behavioral', it could be a complex hypothetical situation requiring demonstration of specific skills, potentially framed by the 'interviewFocus'.

{{else if (eq interviewStyle "simple-qa")}}
**Simple Q&A - Generate 5-10 questions:**
1.  For the 'simple-qa' style, questions should be direct, standalone, and suitable for a straightforward question-and-answer format.
2.  Ensure questions are tailored to the 'interviewType', 'jobTitle', 'jobDescription', 'faangLevel', any 'targetedSkills', and particularly the 'interviewFocus' if provided. The 'interviewFocus' should guide the selection or framing of at least some questions.
3.  Generate 5-10 diverse questions that cover different facets of the 'interviewType'. For example, for "Product Sense," include questions on strategy, execution, metrics, and user understanding, all potentially colored by the 'interviewFocus'.

{{else}}
{{! This block should ideally not be reached if the main flow only handles simple-qa and case-study }}
This interview style ({{{interviewStyle}}}) is not directly handled by this prompt. Take-home assignments are generated by a specialized process.

{{/if}}

{{#if (eq (toLowerCase targetCompany) "amazon")}}
**Amazon-Specific Considerations (if 'targetCompany' is Amazon):**
Pay special attention to Amazon's Leadership Principles.
1.  **Behavioral:** Many questions MUST provide an opportunity to demonstrate these principles. Frame questions using situations or ask for examples (e.g., "Tell me about a time you Insisted on the Highest Standards, even when it was difficult, especially concerning {{{interviewFocus}}}.")
2.  **Product Sense / Technical System Design:** Frame questions to subtly align with principles like Customer Obsession (e.g., "How would you design this system to ensure the best possible customer experience under failure conditions, particularly for {{{interviewFocus}}}?"), Ownership, or Invent and Simplify (e.g., "Propose a significantly simpler approach to solve X problem related to {{{interviewFocus}}}.").
Amazon's Leadership Principles for your reference:
{{#each (raw "${AMAZON_LEADERSHIP_PRINCIPLES_JOINED}")}}
- {{{this}}}
{{/each}}
{{/if}}

**Final Output Format:**
Output the questions as a JSON object with a 'customizedQuestions' key, which is an array of strings.
- For 'simple-qa', this will be an array of 5-10 strings.
- For 'case-study', this will be an array of 5-7 strings.
`,
  customize: (prompt, input) => {
    return {
      ...prompt,
      prompt: prompt.prompt!.replace(
        '${AMAZON_LEADERSHIP_PRINCIPLES_JOINED}',
        AMAZON_LEADERSHIP_PRINCIPLES.join('\n- ')
      ),
    };
  }
});

const customizeInterviewQuestionsMainFlow = ai.defineFlow( // Renamed
  {
    name: 'customizeInterviewQuestionsMainFlow', // Renamed
    inputSchema: CustomizeInterviewQuestionsInputSchema,
    outputSchema: CustomizeInterviewQuestionsOutputSchema,
  },
  async input => {
    // This flow should not be called for 'take-home' directly by the outer function.
    // If it is, the prompt will indicate it's handled elsewhere.
    if (input.interviewStyle === 'take-home') {
        // This should ideally not happen if the outer function `customizeInterviewQuestions` handles delegation.
        // However, as a safeguard:
        return { customizedQuestions: ["Take-home assignments are generated by a specialized process. This path should not have been reached."] };
    }

    const {output} = await mainPrompt(input);
    // Ensure output is not null and customizedQuestions exists
    if (!output || !output.customizedQuestions || output.customizedQuestions.length === 0) {
        // Fallback or error handling for failed generation
        const genericFallback = ["Tell me about yourself.", "Why are you interested in this role?", "Describe a challenging project you worked on.", "What are your strengths?", "What are your weaknesses?"];
        const numQuestions = input.interviewStyle === 'case-study' ? 5 : 7; 
        const selectedFallback = genericFallback.slice(0, Math.min(numQuestions, genericFallback.length));
        return { customizedQuestions: selectedFallback };
    }
    return output!;
  }
);
