
'use server';
/**
 * @fileOverview A specialized AI flow to refine draft interview feedback.
 *
 * - refineInterviewFeedback - A function that takes draft feedback and interview context, returning refined feedback.
 * - RefineInterviewFeedbackInput - The input type for the refineInterviewFeedback function.
 * - RefineInterviewFeedbackOutput - The return type for the refineInterviewFeedback function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
// Assuming these types exist in lib/types - no, they are defined in constants or schemas.
// import type { InterviewType, InterviewStyle } from '@/lib/types'; 
import { GenerateInterviewFeedbackOutputSchema, type GenerateInterviewFeedbackOutput } from '../schemas'; // Import from shared schemas

const InterviewContextSchema = z.object({
  interviewType: z.string(),
  interviewStyle: z.string(),
  faangLevel: z.string(),
  jobTitle: z.string().optional(),
  interviewFocus: z.string().optional(),
  timeWasTracked: z.boolean().describe("Indicates if timeTakenMs was generally available in the draft feedback items.")
});

// Make this an internal constant
const RefineInterviewFeedbackInputSchema = z.object({
  draftFeedback: GenerateInterviewFeedbackOutputSchema.describe(
    'The draft feedback generated by the initial feedback flow. This includes critiques, strengths, areas for improvement, suggestions, ideal pointers, confidence scores, and draft reflection prompts.'
  ),
  interviewContext: InterviewContextSchema.describe(
    'The original context of the interview.'
  ),
});
export type RefineInterviewFeedbackInput = z.infer<
  typeof RefineInterviewFeedbackInputSchema
>;

export type RefineInterviewFeedbackOutput = GenerateInterviewFeedbackOutput; // Type is based on the imported schema's type

export async function refineInterviewFeedback(
  input: RefineInterviewFeedbackInput
): Promise<RefineInterviewFeedbackOutput> {
  return refineInterviewFeedbackFlow(input);
}

const refinePrompt = ai.definePrompt({
  name: 'refineInterviewFeedbackPrompt',
  input: {schema: RefineInterviewFeedbackInputSchema}, // Use internal schema here
  output: {schema: GenerateInterviewFeedbackOutputSchema}, // Use the imported schema from ../schemas
  prompt: `You are an Expert Feedback Polisher AI. Your task is to review and refine DRAFT interview feedback to make it exceptionally clear, concise, actionable, and supportive.
Pay special attention to polishing the 'reflectionPrompts'.

**Original Interview Context:**
- Type: {{interviewContext.interviewType}}
- Style: {{interviewContext.interviewStyle}}
- Level: {{interviewContext.faangLevel}}
{{#if interviewContext.jobTitle}}- Job Title: {{interviewContext.jobTitle}}{{/if}}
{{#if interviewContext.interviewFocus}}- Specific Focus: {{interviewContext.interviewFocus}}{{/if}}
{{#if interviewContext.timeWasTracked}}(Note: Time taken for answers was tracked and may be present in the draft feedback items.){{/if}}

**DRAFT Feedback for Review:**

**Overall Summary (Draft):**
"{{draftFeedback.overallSummary}}"

**Feedback Items (Draft):**
{{#each draftFeedback.feedbackItems}}
---
Question ID: {{this.questionId}}
Question: "{{this.questionText}}"
Answer: "{{this.answerText}}"
{{#if this.timeTakenMs}}(Time taken: {{this.timeTakenMs}} ms){{/if}}
{{#if this.confidenceScore}}(User Confidence: {{this.confidenceScore}}/5){{/if}}

Critique (Draft): "{{this.critique}}"
Strengths (Draft): {{#if this.strengths.length}}{{#each this.strengths}}
- "{{this}}"{{/each}}{{else}}None listed.{{/if}}
Areas for Improvement (Draft): {{#if this.areasForImprovement.length}}{{#each this.areasForImprovement}}
- "{{this}}"{{/each}}{{else}}None listed.{{/if}}
Specific Suggestions (Draft): {{#if this.specificSuggestions.length}}{{#each this.specificSuggestions}}
- "{{this}}"{{/each}}{{else}}None listed.{{/if}}
Ideal Answer Pointers (Draft): {{#if this.idealAnswerPointers.length}}{{#each this.idealAnswerPointers}}
- "{{this}}"{{/each}}{{else}}None listed.{{/if}}
Reflection Prompts (Draft): {{#if this.reflectionPrompts.length}}{{#each this.reflectionPrompts}}
- "{{this}}"{{/each}}{{else}}None listed.{{/if}}
---
{{/each}}

**Your Task: REFINE the draft feedback based on the following criteria.**
Your output MUST be in the same JSON format as the input 'draftFeedback' (keys 'feedbackItems' and 'overallSummary').
Do NOT simply repeat the draft. Provide tangible improvements.

1.  **Clarity & Conciseness:**
    *   Rephrase any jargon or overly complex sentences into simple, direct language.
    *   Eliminate redundancy. Ensure each point is distinct and impactful.
    *   The overall summary should be easy to grasp and provide a clear takeaway.

2.  **Tone:**
    *   Ensure the tone is consistently supportive, encouraging, and constructive. Avoid overly harsh or critical language.
    *   Frame 'areasForImprovement' as opportunities for growth and learning.

3.  **Actionability:**
    *   'SpecificSuggestions' must be highly practical and provide clear, actionable steps the candidate can take.
    *   'AreasForImprovement' should clearly identify what needs work, ideally with a hint towards how.

4.  **Reflection Prompts Polish:**
    *   Review the draft 'reflectionPrompts'. Ensure they are open-ended, encouraging, and genuinely help the user reflect on their answer in relation to their confidence and the AI's feedback.
    *   Make them more insightful and less generic if needed. Ensure they align well with the critique given for that specific answer.

5.  **Completeness & Relevance (Especially for Overall Summary):**
    *   **Pacing Check:** If 'interviewContext.timeWasTracked' is true, critically assess if the draft 'overallSummary' adequately comments on the candidate's pacing and time management. If this aspect is missing or too generic in the draft, enhance this part of the summary.
    *   **Focus Check:** If an 'interviewFocus' was provided, ensure the 'overallSummary' and relevant 'feedbackItems' explicitly address how well the candidate addressed this focus. If this is weak or missing in the draft, strengthen this aspect.
    *   Ensure all feedback components (critique, strengths, areas, suggestions, ideal pointers, reflectionPrompts) are well-developed, distinct, and insightful for each 'feedbackItem'. If any section in the draft feels underdeveloped, generic, or repetitive, enhance it.

6.  **Maintain Original IDs and Structure:**
    *   The 'questionId' for each feedback item must be preserved.
    *   The output must conform to the same JSON structure as the input 'draftFeedback'.

Return ONLY the refined JSON object.
`,
});

const refineInterviewFeedbackFlow = ai.defineFlow(
  {
    name: 'refineInterviewFeedbackFlow',
    inputSchema: RefineInterviewFeedbackInputSchema, // Use internal schema here
    outputSchema: GenerateInterviewFeedbackOutputSchema, // Use the imported schema from ../schemas
  },
  async (input: RefineInterviewFeedbackInput) => {
    // Ensure arrays exist to prevent handlebars errors if they are undefined
    const processedDraftFeedback = {
      ...input.draftFeedback,
      feedbackItems: input.draftFeedback.feedbackItems.map(item => ({
        ...item,
        strengths: item.strengths || [],
        areasForImprovement: item.areasForImprovement || [],
        specificSuggestions: item.specificSuggestions || [],
        idealAnswerPointers: item.idealAnswerPointers || [],
        reflectionPrompts: item.reflectionPrompts || [],
      }))
    };

    const {output} = await refinePrompt({ ...input, draftFeedback: processedDraftFeedback });
    if (!output) {
      throw new Error('AI did not return refined feedback.');
    }
    // Ensure arrays exist in the output as well
    const validatedOutput: RefineInterviewFeedbackOutput = {
        overallSummary: output.overallSummary,
        feedbackItems: output.feedbackItems.map(item => ({
            ...item,
            strengths: item.strengths || [],
            areasForImprovement: item.areasForImprovement || [],
            specificSuggestions: item.specificSuggestions || [],
            idealAnswerPointers: item.idealAnswerPointers || [],
            reflectionPrompts: item.reflectionPrompts || [],
        })),
    };
    return validatedOutput;
  }
);

