[project]
name = "interview-agents-python"
version = "0.1.0"
description = "Multi-agent interview system for Interview AI platform"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "argostranslate>=1.9.6",
    "openai-whisper>=20240930",
]
